version: '3'
services:
  webapp-1:
    image: cheftraining/webapp
  webapp-2:
    image: cheftraining/webapp
    command: --peer webapp-1
  load_balancer:
    image: cheftraining/haproxy
    command: --peer webapp-2 --bind backend:webapp.default
    ports:
      - "8000:80"
